[user]
name = "Marcus André"
email = "hello+github@marcusandre.de"

[ui]
default-command = "status"
# diff.tool = ["difft", "--color=always", "$left", "$right"]

[git]
push-branch-prefix = "man/push-"

# [signing]
# sign-all = true
# backend = "ssh"
# key = "~/.ssh/id_ed25519_sign.pub"

[aliases]
l = ["log"]
d = ["diff"]
rb = ["rebase"]
