[user]
name = "Marcus André"
email = "hello+github@marcusandre.de"

[ui]
editor = "nvim"
default-command = "status"
# diff.tool = ["difft", "--color=always", "$left", "$right"]

[git]
push-branch-prefix = "man/push-"

# [signing]
# sign-all = true
# backend = "ssh"
# key = "~/.ssh/id_ed25519_sign.pub"
