vim.keymap.set("n", "<esc>", "<cmd>noh<cr><esc>", { desc = "Escape and clear hlsearch" })
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("i", "kj", "<esc>")
vim.keymap.set("n", "<leader>oc", "<Cmd>lua require('m.functions').toggle_quickfix()<CR>", { desc = "Quickfix: Toggle" })
