vim.keymap.set("n", "<leader><leader>", "<Cmd>b#<CR>", { desc = "Buffer: Toggle" })
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "Y", "y$")
vim.keymap.set("n", "n", "nzz")
