# Navigation
alias ..="cd .."

# Directory Listings
if [ $(uname -s) == "Linux" ]; then
  alias ls="ls --color"
else
  alias ls="ls -G"
fi

alias ls="ls -GFh"
alias la="ls -la"
alias lh="ls -lah"
alias ls1="ls -1"

# Misc
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias rf="rm -rf"
alias sudo="sudo "
alias week="date +%V"
alias m="make "
alias s="subl ."
alias grep="grep --line-number --color"
alias irc="irssi -n meggesje -c irc.freenode.net"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to clipboard.\n'"
alias colors="printf \"\e[%dm%d dark\e[0m  \e[%d;1m%d bold\e[0m\n\" {30..37}{,,,}"
alias ip="ifconfig | grep 'inet ' | grep -v 127.0.0.1 | cut -d\   -f2"
alias rmds="find . -name \".DS_Store\" | xargs rm"
alias pull="curl -L#"

# Git aliases
alias gl="git log --pretty=oneline --abbrev-commit --graph --decorate"
alias gd="git diff"
alias ga="git add"
alias gbd="git branch -D"
alias gst="git status"
alias gca="git commit -a -m"
alias gm="git merge --no-ff"
alias gpt="git push --tags"
alias gpa="git push --all"
alias gp="git push"
alias grh="git reset --hard"
alias gb="git branch"
alias gcob="git checkout -b"
alias gco="git checkout"
alias gba="git branch -a"
alias gfp="git fetch origin --prune"
alias gr2="git rebase -i HEAD~2"
alias gr3="git rebase -i HEAD~3"

# Vagrant aliases
alias vup="vagrant up"
alias vha="vagrant halt"
alias vst="vagrant status"
alias vdf="vagrant destroy -f; rm -rf .vagrant"

# cd into new directory
function take {
  mkdir -p "$@" && cd "$_";
}

# serve tree via http
function serve {
  python -m SimpleHTTPServer
}
