# Prefix Path
export PATH=/usr/local/bin:$PATH

if [ -d ~/bin ]; then
  export PATH=~/bin:$PATH
fi

# Hail to the Vim, Baby
export EDITOR=vim

# Homebrew Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Initialize rbenv and it's rubies
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Init z
if [ -f ~/bin/z ]; then
  . ~/bin/z
fi

# Call the prompt
if [ -f ~/.bash_prompt ]; then
  source ~/.bash_prompt
fi

# Call the aliases
if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

# Load nvm into shell session
[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh
