# Prefix Path
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

if [ -d ~/bin ]; then
  export PATH=~/bin:$PATH
fi

# Adding Android Development Tools to PATH.
if [ -d ~/bin/adt-bundle-mac-x86_64-20131030 ]; then
  export ANDROID_TOOLS_HOME=~/bin/adt-bundle-mac-x86_64-20131030/sdk/tools
  export ANDROID_PLATFORM_TOOLS_HOME=~/bin/adt-bundle-mac-x86_64-20131030/sdk/platform-tools
  export PATH=$PATH:$ANDROID_TOOLS_HOME:$ANDROID_PLATFORM_TOOLS_HOME

  if [[ `uname` == "Darwin" ]]; then
    export JAVA_HOME=$(/usr/libexec/java_home)
  fi
fi

# Hail to the Vim, Baby
export EDITOR=vim

# Homebrew Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Initialize rbenv and it's rubies
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Init z
if [ -f ~/bin/z ]; then
  . ~/bin/z
fi

# Call the prompt
if [ -f ~/.bash_prompt ]; then
  source ~/.bash_prompt
fi

# Call the aliases
if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

# Source bash_completion manualy if it's exist
# There are companies where you don't get admin rights. :(
[ -s $HOME/bin/git-completion.bash ] && source $HOME/bin/git-completion.bash

# Load nvm into shell session
[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh
