tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'caskroom/cask'
tap 'restic/restic'
brew 'bash'
brew 'bash-completion'
brew 'fzf'
brew 'git'
brew 'git-extras'
brew 'httpie'
brew 'hub'
brew 'mas'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'restic'
brew 'stow'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-python3', 'override-system-vi']
brew 'z'
cask '1password'
cask 'alfred'
cask 'flux'
cask 'google-chrome'
cask 'keepingyouawake'
cask 'sketch'
cask 'spectacle'
cask 'vagrant'
cask 'virtualbox'
mas 'Reeder', id: 880001334
mas 'Tweetbot', id: 557168941
