theme = "tokyonight"

[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-j = "shrink_selection"
C-k = "expand_selection"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.space]
X = ":buffer-close-others"
q = ":quit"
w = ":write"
x = ":buffer-close"
"space" = ":buffer-previous"

[keys.normal.space.o]
f = [":toggle-option auto-format"]
i = [":toggle-option lsp.inlay-hints"]

[keys.normal.space.l]
f = [":format"]
g = [":sh gh browse"]
