theme = "poimandres"

[editor]
bufferline = "always"
color-modes = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-j = "shrink_selection"
C-k = "expand_selection"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.space]
q = ":quit-all"
x = ":buffer-close"
X = ":buffer-close-others"
w = ":write"
"space" = ":buffer-previous"
