theme = "nord"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
color-modes = true
auto-pairs = true
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false
