[user]
name = "Marcus André"
email = "102828+marcusandre@users.noreply.github.com"

[signing]
sign-all = true
backend = "ssh"
key = "~/.ssh/id_ed25519_personal_sign.pub"

[ui]
default-command = "log"
diff-editor = "diffedit3"
