tap homebrew/versions
upgrade
update
install ack
install antigen
install bash
install bash-completion
install curl
install findutils
install fzf
install git
install git-extras
install go
install htop-osx
install httpie
install jq
install lua52
install md5sha1sum
install nvm
install openssl
install osxfuse
install pandoc
install pwgen
install rbenv
install reattach-to-user-namespace
install rename
install ruby-build
install ssh-copy-id
install the_silver_searcher
install tmux
install tree
install vim --with-lua --with-luajit --override-system-vi
install wget
install z
install zsh
cleanup --force
