#!/usr/bin/env bash

DIR=$HOME/.go

if [ ! -d "$DIR" ]; then
  git clone https://github.com/golang/go.git "$DIR"
  cd $DIR/src && git checkout go1.4.2 && ./all.bash
else
  echo "Golang seems to be already installed."
fi
