#!/usr/bin/env bash

set -e

TARGET=~/.vim/autoload/plug.vim
URL=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [ ! -d "$TARGET" ]; then
  curl -fLo $TARGET --create-dirs $URL
  ln -sf ~/.vim ~/.nvim
  vim +PlugInstall +qall
else
  vim +PlugUpgrade +qall
fi
