#!/usr/bin/env bash

set -e

VIMDIR=~/.vim
NVIMDIR=~/.config/nvim
PLUGVIM=$VIMDIR/autoload/plug.vim
REMOTE=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

function link() {
  test -h $VIMDIR/snippets || ln -sf $(pwd)/vim/snippets $VIMDIR/snippets
  test -h $NVIMDIR || mkdir -p $NVIMDIR
  test -h $NVIMDIR || ln -sf $VIMDIR $NVIMDIR
  test -h $NVIMDIR/init.vim || ln -s ~/.vimrc $NVIMDIR/init.vim
}

function install() {
  curl -fLo $PLUGVIM --create-dirs $REMOTE
  vim +PlugInstall +qall
}

function upgrade(){
  vim +PlugUpgrade +PlugUpdate +PlugClean +qall
}

if [ ! -f "$PLUGVIM" ]; then
  install && link
else
  upgrade && link
fi
