return {
  'nvim-treesitter/nvim-treesitter',
  dependencies = {
    'nvim-treesitter/nvim-treesitter-textobjects',
  },
  config = function()
    require('nvim-treesitter.configs').setup({
      ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'diff',
        'dockerfile',
        'dot',
        'fish',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gomod',
        'gosum',
        'html',
        'http',
        'java',
        'javascript',
        'jq',
        'json',
        'json5',
        'lua',
        'make',
        'markdown',
        'nix',
        'php',
        'python',
        'r',
        'regex',
        'ruby',
        'rust',
        'scss',
        'sql',
        'terraform',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'yaml',
      },
      highlight = { enable = false },
      indent = { enable = true, disable = { 'python' } },
    })

    pcall(require('nvim-treesitter.install').update({ with_sync = true }))
  end,
}
